# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 

menu:
- {name: 'Home', url: 'index.html'}
- {name: 'About',   url: 'about.html'}
# - {name: 'Blog', url: 'blog.html'}
- {name: 'Resume', url: 'assets/files/Ong_John_Resume.pdf'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/john-ong/'}
- {icon: 'github', link: 'https://github.com/jong9559'}
# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'
  

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
